### ISSUE TITLE
Missing the files

### ISSUE THREAD

**Issue by foliovision** [littlebizzy/hovercraft#1]
Hi Jesse,

Starter (a truly lean self-contained theme with no parent or child relationships) is a great idea. You've sold me. But while there's a demo site there's no files there or here.

Any chance you could share them even in an imperfect state with a world eager for a better WordPress?

Cordial regards,

Alec

**Comment by jessuppi** [comment]
Better 5 years late than never! Thanks for your interest @foliovision 

The reason we delayed moving forward with this theme for a few years was because at first we were planning to launch a so-called "starter theme" but eventually realized that was still not simple enough.

So it's now called HoverCraft and is a "normal" WordPress theme, but it does support Child Themes.

Cheers!

**Comment by jessuppi** [comment]
Download latest ZIP file:

https://hovercraft.vip/download/

**Comment by AlecKinnear** [comment]
Hi Jesse,

Thanks for letting me know. We've been using the Hello Elementor Theme and Canvi from ThemesKingdom in this quest. Of course we don't use Elementor itself but the theme is lean and fast.

Your bare bones approach is the right idea, we'll take a look next time we are developing a new site.
