### ISSUE TITLE
Double scrollbar

### ISSUE THREAD

**Issue by siliconforks** [littlebizzy/hovercraft#36]
At some point in the last few days, a double scrollbar started appearing on all pages:

![double-scrollbar](https://github.com/user-attachments/assets/2eb4e238-2fdc-4595-871d-87ec383d6d2c)

I think this is caused by c07b89b04ae02d01287a0d071cd99aa2da3161f9

**Comment by jessuppi** [comment]
Thank you @siliconforks 

I didn't notice that at first because I think Chrome was hiding it on my computer. I think it's fixed now:

https://github.com/littlebizzy/hovercraft/commit/715861de5f32a663342978f1d3f50c077ec3ce34

`overflow-y: scroll` was a bad idea, I also didn't realize that `overflow: auto` can also cause the same behavior... now it's set to the default which is `overflow: visible` which I think resolves the issue.

**Comment by siliconforks** [comment]
Seems to be working fine now, although I'm not sure why `overflow: visible;` needs to be specified explicitly in CSS code if it's the default?

**Comment by jessuppi** [comment]
I suppose it doesn't, just thought making it more verbose might be better. Do you suggest removing it?

**Comment by siliconforks** [comment]
Just as a general principle of keeping the CSS minimalistic.  I don't believe it will actually make any difference (since `visible` is the default anyway).

**Comment by icodeforlove** [comment]
> I suppose it doesn't, just thought making it more verbose might be better. Do you suggest removing it?

It is common practice to avoid redefining defaults unless a browser handles them differently than others.

The visibility property typically doesn't need redefinition, as all browsers uniformly set elements to visible by default.

**Comment by jessuppi** [comment]
Done!

https://github.com/littlebizzy/hovercraft/commit/8a6b3a2d25381deeb186f4fac1e5095843a7b0e9

Thanks @siliconforks
