### ISSUE TITLE
cart

### ISSUE THREAD

**Issue by ghost** [littlebizzy/hovercraft#6]
cart widget is currently on menu-desktop. (template-parts/navigation.php)
this is not desirable since it is needed on desktop as well.
i moved it to header-right offline but its not ready for production yet. it needs padding etc.
will commit once ready.

**Comment by ghost** [comment]
another solution may be to include it in the offcanvas menu.(on header.php)

**Comment by jessuppi** [comment]
Okay interesting @yamanmucahit 

I don't think I understand fully what you mean, are you saying the cart icon is missing on mobile?

**Comment by ghost** [comment]
yes @jessuppi. that must have been a typo i meant "needed on mobile as well".

**Comment by jessuppi** [comment]
Thanks @yamanmucahit  there should be an offcanvas cart now although it's a bit janky...

https://github.com/littlebizzy/hovercraft/tree/0.1.117

I do kinda like same as you, the cart icon in the mobile header instead of offcanvas, but I have noticed that on many WordPress sites there's not enough space due to logo + site name.

**Comment by ghost** [comment]
Thank you @jessuppi. Can the string be `<?php esc_html(_e('My Cart', 'hovercraft'))?>`? Its best practice to use gettext functions when dealing with strings.

**Comment by jessuppi** [comment]
Done: https://github.com/littlebizzy/hovercraft/commit/e5d6d2796f90d6c7ee089b62dce69303be4be3e9

Probably will have to go through all template files later on to improve translation strings.

Thanks!
